### ISSUE TITLE
Could you add a way to disable certain tweaks in a config file?

### ISSUE THREAD

**Issue by chexo3** [Amb0s/vanilla-fixes#2]
For instance, I don't want to use the boat tweak. I _could_ go into mixins.json and zap that mixin, but that would be a lot of effort. Plus, this lets you have multiple versions of the behavior. Maybe one behavior for boat drop fix is that instead of simply dropping itself whenever, it drops if you break it with an empty hand, or while sneaking. Or maybe sneak right clicking causes it to commit die and drop itself. This would preserve the normal behavior of crashed boats or arrow shot boats not returning a boat item while providing methods of retrieval.

**Comment by Amb0s** [comment]
Implemented in 5.1.0.
