### ISSUE TITLE
Mod makes tools mine insanely fast

### ISSUE THREAD

**Issue by scaldings** [Amb0s/vanilla-fixes#4]
Here's two videos to showcase, while using the mod, the tools mine at twice (if not more) the intended speed:
With the mod installed: https://streamable.com/sbyc6v
Without the mod installed: https://streamable.com/v0tkch
I apologize for the choppy footage, couldn't get my recorder settings to work properly.

**Comment by Amb0s** [comment]
It should be fixed in the last release, open a new ticket if it's still not fixed. Thank you for your report.
